# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tsinghua International Relations Data and Computing Lab
email: thudcl@163.com
description: The Tsinghua International Relations Data and Computing Lab (THU-DCL) is a dynamic research group at Tsinghua University. Our aim is to explore and understand the complexity of international relations data and methods.
baseurl: ""
url: "thudcl.github.io"

include:
  - .htaccess
  - _pages
  - files

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


theme: jekyll-theme-cayman
